"" Basic Functionality
call pathogen#runtime_append_all_bundles()          " pathogen
call pathogen#helptags()
filetype plugin indent on       " load file type plugins + indentation


"" General vim options
set encoding=utf-8
set nocompatible
set showcmd                     " display incomplete commands
set scrolloff=3                 " min lines above or below cursor
set visualbell                  " I hate the acoustic bell
set cursorline                  " highlight current line
set nobackup                    " git/hg
set nowb
set noswapfile                  " No swafile because git/hg
set relativenumber              " show line numbers from current line to calc distances
set guioptions-=T               " don't show toolbar
set guioptions-=m               " don't show menubar
set guioptions-=l               " remove scrollbars
set guioptions-=r
set guioptions-=R
set guioptions-=L
au FocusLost * :wa              " Save on lost focus

set undodir=~/.vim_runtime/undodir
set undofile                    " creates a <FILENAME>.un~ for eternal editing

"" wildmenu - Ignore files you never want to edit (hopefully)
if has("wildmenu")
  set wildmenu                    " autocompletion
  set wildmode=list:longest       " show all
  set wildignore+=*.a,*.o
  set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png
  set wildignore+=.DS_Store
  set wildignore+=*~,*.swp,*.tmp
  set wildignore+=*/.git/*,*/.hg/*,*/.svn/*   " for Linux/MacOSX
  "set wildignore+=.git\*,.hg\*,.svn\*         " for Windows
endif

"" Hande lines
set textwidth=79
set formatoptions=qrn1
set colorcolumn=85
set wrapmargin=79
"" Whitespace
"set nowrap                      " don't wrap lines
"set wrap
set cindent
set smartindent                 " Helps indenting after/before specific keywords
set autoindent                  " keep indent, when indented
"set tabstop=2 shiftwidth=2      " a tab is two spaces
set tabstop=2
"set expandtab                   " use spaces, not tabs
set backspace=indent,eol,start  " backspace through everything in insert mode


"" Look and feel
syntax enable
set background=dark
let g:solarized_contrast="high"    "default value is normal
let g:solarized_visibilty="high"
let g:solarized_termtrans=1
let g:solarized_termcolors=256
colorscheme solarized
set splitright                  " split windows always vertically
set t_Co=256                    " Explicitly tell vim terminal features

function ToggleBackgroundColor()
  if (&background == 'light')
    set background=dark
    echo "background -> dark"
  else
    set background=light
    echo "background -> light"
  endif
endfunction


"" Searching
noremap / /\v
vnoremap / /\v
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter`

set gdefault                    " replacing globally is default
set hlsearch                    " highlight matches
set showmatch                   " show matches
set incsearch                   " incremental searching

""clear search, it looks ugly:
nnoremap <silent><leader>/ :noh<cr>

"" Window movement
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

"" Buffers
map <leader>bd :Bclose<cr>
map <leader>cd :cd %:p:h<cr>
nmap <leader>w :w!<cr>
map <right> :bn<cr>
map <left> :bp<cr>

"" Tab configuration
map <leader>tn :tabnew<cr>
map <leader>te :tabedit
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove


command! Bclose call <SID>BufcloseCloseIt()
function! <SID>BufcloseCloseIt()
   let l:currentBufNum = bufnr("%")
   let l:alternateBufNum = bufnr("#")

   if buflisted(l:alternateBufNum)
     buffer #
   else
     bnext
   endif

   if bufnr("%") == l:currentBufNum
     new
   endif

   if buflisted(l:currentBufNum)
     execute("bdelete! ".l:currentBufNum)
   endif
endfunction

" Bash like keys for the command line
cnoremap <C-A> <Home>
cnoremap <C-E> <End>
cnoremap <C-K> <C-U>
cnoremap <C-P> <Up>
cnoremap <C-N> <Down>

"" Change keyboard shortcuts
let mapleader = ','
nnoremap <leader>e <C-w><C-v><C-l>:e $MYVIMRC<cr>
map <F9>  :call ToggleBackgroundColor()<CR>
inoremap jk <Esc>                                   " Hardcore vim

"" Tagbar plugin
let g:taskbar_usearrows = 1
nnoremap <leader>l :TagbarToggle<CR>


"" vimorganizer:
au! BufRead,BufWrite,BufWritePost,BufNewFile *.org 
au BufEnter *.org            call org#SetOrgFileType()
let g:org_command_for_emacsclient = 'emacsclient'

function! OrgCustomColors()
    hi! Org_Drawer guifg=#586e75 ctermfg=magenta
    hi! Org_Drawer_Folded guifg=#586e75 ctermfg=magenta gui=bold cterm=bold
    hi! Org_Property_Value guifg=#657b83 ctermfg=magenta
    hi! Org_Block guifg=#586375 ctermfg=magenta
    hi! Org_Date guifg=#657b83 ctermfg=magenta gui=underline cterm=underline
endfunction


"" Utl
let g:utl_cfg_hdl_scm_http="silent !chromium-browser '%u#%f' &" 

"" YankRing
nnoremap <silent> <F12> :YRShow<cr>

"" CtrlP
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

let g:ctrlp_custom_ignore = '\.git$\|\.hg$\|\.svn$'
" let g:ctrlp_custom_ignore = {
"   \ 'dir':  '\.git$\|\.hg$\|\.svn$',
"   \ 'file': '\.exe$\|\.so$\|\.dll$',
"   \ 'link': 'some_bad_symbolic_links',
"   \ }


"" Powerline
set laststatus=2
let g:Powerline_symbols= 'unicode'


"" Rainbow parentheses
map <leader>r :RainbowParenthesesToggle<cr>
au VimEnter * RainbowParenthesesToggle


"" XNS
au BufNewFile,BufRead xns.in set filetype=xns


"" Standards:
" Number of spaces to use for an indent.
" Python: 4 spaces
" C: 8 spaces (pre-existing files) or 4 spaces (new files)
au BufRead,BufNewFile *.py,*pyw set shiftwidth=4
au BufRead *.c,*.h set shiftwidth=8
au BufNewFile *.c,*.h set shiftwidth=4

" Number of spaces that a pre-existing tab is equal to.
" For the amount of space used for a new tab use shiftwidth.
" Python: 4
" C: 4
au BufRead,BufNewFile *py,*pyw,*.c,*.h set tabstop=4

" Replace tabs with the equivalent number of spaces.
" Also have an autocmd for Makefiles since they require hard tabs.
" Python: yes
" C: no
" Makefile: no
au BufRead,BufNewFile *.py,*.pyw set expandtab
au BufRead,BufNewFile *.c,*.h set noexpandtab
au BufRead,BufNewFile Makefile* set noexpandtab

" Use the below highlight group when displaying bad whitespace is desired
" highlight BadWhitespace ctermbg=red guisp=red gui=undercurl guifg=NONE guibg=NONE

" Display tabs at the beginning of a line in Python mode as bad.
" au BufRead,BufNewFile *.py,*.pyw match BadWhitespace /^\t\+/
" Make trailing whitespace be flagged as bad.
" au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/

" Wrap text after a certain number of characters
" Python: 120
" C: 120
au BufRead,BufNewFile *.py,*.pyw,*.c,*.h set textwidth=120

" Turn off settings in 'formatoptions' relating to comment formatting.
" - c : do not automatically insert the comment leader when wrapping based on
"    'textwidth'
" - o : do not insert the comment leader when using 'o' or 'O' from command mode
" - r : do not insert the comment leader when hitting <Enter> in insert mode
" Python: not needed
" C: prevents insertion of '*' at the beginning of every line in a comment
au BufRead,BufNewFile *.c,*.h set formatoptions-=c formatoptions-=o formatoptions-=r

" Use UNIX (\n) line endings.
" Only used for new files so as to not force existing files to change their
" line endings.
" Python: yes
" C: yes
au BufNewFile *.py,*.pyw,*.c,*.h set fileformat=unix'

"" Rawland's Python IDE:
" highlight variable under cursor (not smart)
" " Python: yes
" " C: yes
 au BufRead,BufNewFile *.py,*.pyw,*.c  autocmd CursorMoved * silent! exe printf('match IncSearch /\<%s\>/', expand('<cword>')))
