# Check style:
proof:
	echo "weasel words: "
	sh dotfiles/goodstyle/weasel.sh *.tex
	echo
	echo "passive voice: "
	sh dotfiles/goodstyle/passive.sh *.tex
	echo
	echo "duplicates: "
	perl dotfiles/goodstyle/illusions.sh *.tex
