export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="rawland"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
#plugins=(git colorize colored-man-pages lol command-not-found gnu-utils history-substring-search compleat zsh-syntax-highlighting zsh-autosuggestions)
plugins=(git colorize autojump colored-man-pages command-not-found gnu-utils history-substring-search desk)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=$PATH:/usr/local/bin/:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:$HOME/dotfiles/bin

# Enhance system by local
export PATH=$HOME/local/bin:$PATH
export INCLUDE=$HOME/local/include:$INCLUDE
export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig:$PKG_CONFIG_PATH
export LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH
export MANPATH=$HOME/local/share/man:$MANPATH

# Python
export PYTHONPATH=$HOME/local/lib/site-python
export PATH=$PATH:$HOME/.local/bin
# Go
export GOPATH=$HOME/local/src/go
export PATH=$PATH:$GOPATH/bin


# Terminal 256 colors:
export TERM="xterm-256color"
export _Z_NO_RESOLVE_SYMLINKS="true"
export EDITOR="vim"

vman() { man $* | col -b | vim -c 'set ft=man nomod nolist' -; }
alias vman='vman'
alias cat='colorize'

# Common exports:
export TERM="xterm-256color"
export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export CLICOLOR=1
export LSCOLORS=ExGxFxDxCxHxHxCbCeEbEb
export LC_CTYPE=en_US.utf-8
export LESS=FRSX
export FIGNORE=$FIGNORE:.hi:.pyc:.o
export IGNOREEOF=2

bindkey -v

# vi style incremental search
bindkey '^R' history-incremental-search-backward
bindkey '^S' history-incremental-search-forward
bindkey '^P' history-search-backward
bindkey '^N' history-search-forward

autoload edit-command-line
zle -N edit-command-line
bindkey '^Xe' edit-command-line

# CTRL-SPACE accept autosuggestion:
bindkey '^ ' autosuggest-accept

alias mmv='noglob zmv -W'
alias l='ls'

# RZ Cluster specific:
if [ -n $WORK ]; then
  if [[ $WORK == "/work/rs169182" ]]; then

    export HOSTTYPE="rzbull"
    export PATH=$PATH:/home/sw_cats/bin

    # Coding:
    module switch intel intel/14.0

    # Visualization:
    module load GRAPHICS
    module load paraview/4.4.0

    # Engineering:
    module load TECHNICS
  fi
fi

alias ls='ls --color -h --group-directories-first'

# because I prefer gitgoodies:
unalias gg

# fasder!
alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selection
alias v='f -e vim'       # quick opening files with vim
alias m='f -e mplayer'   # quick opening files with mplayer
alias o='a -e xdg-open'  # quick opening files with xdg-open


# location specific:
source ~/.zshrc_local
