export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="rawland"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git colorize colored-man-pages lol command-not-found gnu-utils history-substring-search compleat zsh-syntax-highlighting zsh-autosuggestions)

skip_global_compinit=1
source $ZSH/oh-my-zsh.sh

# Customize to your needs...
#unsetopt correct_all

# Customize to your needs...
export PATH=$PATH:/usr/local/bin/:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:/home/rawland/bin
export PATH=$PATH:/home/rawland/dotfiles/bin
export PATH=$PATH:/home/siegbert/bin

# Enhance system by local
export PATH=$HOME/local/bin:$PATH
export INCLUDE=$HOME/local/include:$INCLUDE
export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig:$PKG_CONFIG_PATH
export LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH
export MANPATH=$HOME/local/share/man:$MANPATH
export PYTHONPATH=$HOME/local/lib/site-python

# Terminal 256 colors:
export TERM="xterm-256color"

. ~/dotfiles/zsh/z/z.sh
#    function precmd() {
#    _z --add "#(pwd -P)"
#    }
#set $_Z_NO_RESOLVE_SYMLINKS
export _Z_NO_RESOLVE_SYMLINKS="true"

export EDITOR="vim"

vman() { man $* | col -b | vim -c 'set ft=man nomod nolist' -; }
alias vman='vman'
alias cat='colorize'

# Common exports:
export TERM="xterm-256color"
export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export CLICOLOR=1
export LSCOLORS=ExGxFxDxCxHxHxCbCeEbEb
export LC_CTYPE=en_US.utf-8
export IGNOREEOF=1
export LESS=FRSX

bindkey -v

# vi style incremental search
bindkey '^R' history-incremental-search-backward
bindkey '^S' history-incremental-search-forward
bindkey '^P' history-search-backward
bindkey '^N' history-search-forward

autoload edit-command-line
zle -N edit-command-line
bindkey '^Xe' edit-command-line

# CTRL-SPACE accept autosuggestion:
bindkey '^ ' autosuggest-accept

alias mmv='noglob zmv -W'
alias l='ls'


# Ctrl-Z instead of fg
fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

# RZ Cluster specific:
if [ -n $WORK ]; then
  if [[ $WORK == "/work/rs169182" ]]; then

    export HOSTTYPE="rzbull"
    export PATH=$PATH:/home/sw_cats/bin
    export PATH=$PATH:/home/rs169182/bin
    export PATH=$PATH:/home/rs169182/dotfiles/bin
    export PATH=$PATH:/home/rs169182/.local/bin

    module switch intel intel/14.0
    module load GRAPHICS
    module load paraview/4.4.0
  fi
fi

source ~/.zshrc_local
