# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# When displaying prompt, write previous command to history file so that,
# any new shell immediately gets the history lines from all previous shells.
PROMPT_COMMAND='history -a'

# Set history file length.(See HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=10000
HISTFILESIZE=20000

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

force_color_prompt=yes

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -lhFA'
alias la='ls -AF'
alias l='ls -Fl --group-directories-first'


# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

export EDITOR=vim

MNAZIMS_DEFAULT_COLOR="[00m"
MNAZIMS_GRAY_COLOR="[37m"
RS_REDISH="[31m"
MNAZIMS_GREEN_COLOR="[32m"
MNAZIMS_ORANGE_COLOR="[33m"
RS_TURQOISE="[36m"
if [ `id -u` == '0' ]; then
  MNAZIMS_USER_COLOR=$RS_TURQOISE
else
  MNAZIMS_USER_COLOR=$RS_REDISH
fi


export MNAZIMS_BASEPROMPT='\n\e${MNAZIMS_USER_COLOR}\u\
\e${MNAZIMS_GRAY_COLOR}@\e${MNAZIMS_ORANGE_COLOR}\h \
\e${MNAZIMS_GRAY_COLOR}in \e${MNAZIMS_GREEN_COLOR}\w\
\e${MNAZIMS_DEFAULT_COLOR}'
#export PS1="${MNAZIMS_BASEPROMPT}
#$ "
export PS1='\[\033[01;32m\]\u\[\033[01;34m\]@\[\033[01;31m\]\h\[\033[00;34m\]:\[\033[01;34m\]\w\[\033[00;34m\]\[\033[01;32m\]> \[\033[00m\]'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f ~/.bash_local ]; then
    . ~/.bash_local
fi


# vman:

vman() { man $* | col -b | vim -c 'set ft=man nomod nolist' -; }
alias vman='vman'

# Common exports:
export TERM="xterm-256color"
export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export CLICOLOR=1
export LSCOLORS=ExGxFxDxCxHxHxCbCeEbEb
export LC_CTYPE=en_US.utf-8
export IGNOREEOF=1
export PYTHONDONTWRITEBYTECODE=1
export LESS=FRSX

# Z:
. ~/dotfiles/zsh/z/z.sh
